"""
Definition of global constant variables
"""
"""
ACCESS_TOKEN = ""
API_VERSION = ""
SERVER_ADDRESS = ""
PROJECT_NAME = ""
REPO_NAME = ""
"""

FAILED = "FAILED"
SUCCESS = "SUCCESS"
IN_PROGRESS = "IN_PROGRESS"
CONFLICT = "CONFLICT"
NO_STATUS = "NO_STATUS"
INVALID = "INVALID"
MERGED = "MERGED"
READY_TO_MERGE = "READY_TO_MERGE"

VALID_STATS = [FAILED, SUCCESS, IN_PROGRESS, CONFLICT, MERGED, READY_TO_MERGE]

APP_ICON = "mk_icon.ico"

HORIZONTAL_SPACE = 5
HORIZONTAL_PADDING = 10
VERTICAL_SPACE = 5
VERTICAL_PADDING = 10


DEFAULT_WIN_TOP = 10
DEFAULT_WIN_LEFT = 10
DEFAULT_WIN_WIDTH = 300

DEFAULT_BTN_HEIGHT = 30
DEFAULT_BTN_WIDTH = 70
DEFAULT_LABEL_HEIGHT = 20
DEFAULT_CONTAINER_HEIGHT = 220

OPTIONS_WIDTH = 320

EDIT_LINE_STYLESHEET_DEFAULT = "border:1px solid black;"
EDIT_LINE_STYLESHEET_CHANGED = "border:1px solid red;"
